services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: bookbuddy_user
      POSTGRES_PASSWORD: bookbuddy_password
      POSTGRES_DB: bookbuddy_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: